name: Publish libs

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-22.04
    name: Charmhub upload orc8r-libs
    steps:
      - uses: actions/checkout@v3
      - name: Select Charmhub channel
        uses: canonical/charming-actions/channel@2.2.2
        id: channel
      - uses: canonical/charming-actions/upload-charm@2.2.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          upload-image: "false"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: "${{ steps.channel.outputs.name }}"

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          set -eux
          orc8r_libs="
          charms.magma_orc8r_libs.v0.orc8r_base 
          charms.magma_orc8r_libs.v0.orc8r_base_db
          "
          for lib in ${orc8r_libs}; do
            echo "Publishing ${lib}"
            (charmcraft publish-lib ${lib})
          done
